tasks:
  - name: "init script"
    env:
      FRONTEND_PORT: 3000
      BACKEND_PORT: 4567
      FRONTEND_URL: "$(gp url $FRONTEND_PORT)"
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4567